# Setup, we use custom characters not in default Terminal in oh-my-posh
if [[ $TERM_PROGRAM == "ghostty" ]]; then
    eval "$(oh-my-posh init zsh --config $HOME/.config/oh-my-posh.json)"
fi

# zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ $TERM_PROGRAM == "ghostty" ]]; then
    # ZSH HIGHLIGHT COLORS
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
    ZSH_HIGHLIGHT_STYLES[command]='fg=#40a02b'
    ZSH_HIGHLIGHT_STYLES[function]='fg=#40a02b'
    ZSH_HIGHLIGHT_STYLES[builtin]='fg=#40a02b,bold'
    ZSH_HIGHLIGHT_STYLES[unknown]='fg=#e5c890'
    ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#d20f39,bold'
fi
export HELIX_RUNTIME=/usr/local/libexec/helix/runtime

# History settings
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE

# Extended tab completion
autoload -Uz compinit
compinit

# Use Ctrl-t to swap paramters (words)
bindkey '^T' transpose-words
bindkey '^[t' transpose-chars

# Prettify man pages
export LESS_TERMCAP_mb=$'\e[3m' # $(tput blink; tput setaf 4)
export LESS_TERMCAP_md=$'\e[1m\e[92m' # $(tput bold; tput setaf 10)
export LESS_TERMCAP_me=$'\e[0m' # $(tput sgr0)
export LESS_TERMCAP_us=$'\e[32m' # $(tput setaf 2)
export LESS_TERMCAP_ue=$'\e[0m' # $(tput sgr0)

# Python
if [[ -d /Library/Frameworks/Python.framework/Versions/Current/bin ]]; then
    export PATH="/Library/Frameworks/Python.framework/Versions/Current/bin:$PATH"
fi

# Color full-color lookup of hex values
color() {
    if [[ $# -eq 1 ]]; then
        hex="${1#"#"}"
        [[ ${#hex} -eq 3 ]] && hex="${hex:0:1}${hex:0:1}${hex:1:1}${hex:1:1}${hex:2:1}${hex:2:1}"
        red=$((16#${hex:0:2})); grn=$((16#${hex:2:2})); blu=$((16#${hex:4:2}))
    elif [[ $# -eq 3 ]]; then
        red=$1; grn=$2; blu=$3
        hex=$(printf '%02x%02x%02x' ${red} ${grn} ${blu})
    else
        printf "color (hex_value|red green blue)\n"
    fi
    printf "#${hex:u} = ▕\033[38;2;${red};${grn};${blu}m████\033[0m▏\n"
}

# whatsmyip
myip() {
    print $(curl -s ifconfig.me)
}


